platform :ios, '13.0'

use_frameworks!
inhibit_all_warnings!

workspace 'Example'
project 'Example'

target 'Example' do
  # Realm
  pod 'RealmSwift', '5.0.0-beta.2'

  # Rx
  pod 'RxSwift', '5.0.1'

  # Reactive
  pod 'ReactiveSwift', '6.2.0'

  pod 'RealmWhatever', :path => '../'

  script_phase :name => 'SwiftFormat', :execution_position => :before_compile, :script =>
  <<-HEREDOC
  if which swiftformat >/dev/null; then
    swiftformat --swiftversion 5.0 --disable redundantSelf ./Example
  else
    echo "warning: SwiftFormat not installed, download it from https://github.com/nicklockwood/SwiftFormat"
  fi
  HEREDOC
end
